### ISSUE TITLE
Expand command line argument filepath

### ISSUE THREAD

**Issue by tomasalagoa** [jmg-duarte/nabu#12]
When providing a filepath it should be expanded from the project root directory so an argument like `../test-dir/` should expand to to the repo's fullpath

**Comment by jmg-duarte** [comment]
Rust's [`fs::canonicalize`](https://doc.rust-lang.org/std/fs/fn.canonicalize.html) should work for our purposes.
It fails if the file is missing, but we need the file to be present so 🤷

**Comment by jmg-duarte** [comment]
Fixed in #13
