### ISSUE TITLE
flexi_logger error working with local time

### ISSUE THREAD

**Issue by tomasalagoa** [jmg-duarte/nabu#9]
Error message:
`[flexi_logger][ERRCODE::Time] flexi_logger has to work with UTC rather than with local time, caused by IndeterminateOffset`

Documented in:
[issue #99 of flexi_logger](https://github.com/emabee/flexi_logger/issues/99)
[rustsec](https://rustsec.org/advisories/RUSTSEC-2020-0159)

**Comment by jmg-duarte** [comment]
An easy fix is to simply move to another library. Logging libraries are
dime-a-dozen and I didn't pick flexi for any specific reason.

A segunda, 7 de mar de 2022, 22:26, Tomás Alagoa ***@***.***>
escreveu:

**Comment by jmg-duarte** [comment]
Ah I see now, a simple change in configuration should suffice. Maybe check how to use UTC time in `flexi_logger`
